[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { workspace = true }
systems = { workspace = true }
anyhow = "1.0.95"
bytemuck = { version = "1.16", features = [ "derive" ] }
image = "0.25.5"
wgpu = "24.0.1"
cgmath = "0.18.0"
rand = "0.9.0"
